### ISSUE TITLE
Use supermodel instead of interface for Dexterity schema

### ISSUE THREAD

**Issue by tomgross** [plone/bobtemplates.plone#104]
Currently in the Dexterit schema the interface is referenced for the schema (see https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/profiles/default/types/%2Bpackage.dexterity_type_name%2B.xml.bob#L27)
To enhance TTW exchangeability and remove a potential error cause (if you add a supermodel and don't remove the schema interface Plone will still use the schema interface) it would be good to ship the template with a supermodel-xml prepared.

**Comment by tisto** [comment]
Personally I prefer to use zope.schema since it can be better tested and it is much more readable for humans than an XML schema. The TTW functionality is nice a nice thing to show to people that are new to Plone, but nothing I would really recommend to use in real-world projects. I'm aware that people have different opinions on that though. 

bobtemplates.plone should reflect what we as a community consider to be best practice. I'm aware that it is not easy to reach an agreement on every single detail. :)

**Comment by MrTango** [comment]
Maybe we can support both in the new and smaler plone_dx_contenttype template and ask while creating the CT. As the xml-model is the way plone.app.contentypes goes I would use this as default.
And it also make it possible to have the roundtrip.
