### ISSUE TITLE
get rid of bootstrap.py

### ISSUE THREAD

**Issue by iham** [plone/bobtemplates.plone#137]
best practise nowadays is to use `$ virtualenv` and `$ pip install zc.buildout`
this works with plone 4 and 5 as far as i know.

i would like to delete the bootstrap file and change the docs.

any problems i don't see?

**Comment by do3cc** [comment]
It is not yet officially best practice.
Some people in plone complain (rightfully so imho) that if we consider pip install a better best practice, we should first start to bring that up in zc.buildout:
https://github.com/buildout/buildout/issues/289
If you want to work on that, please do so! Nobody is against that, but first, docs and tests in zc.buildout should be updated.

**Comment by iham** [comment]
i am currently working on plone.bobtemplates as i want to add support for plonetheme.barceloneta and don't have the time to start fixing/testing/documenting zc.buildout as i am fine with how it works right now.
(using pip with or without requirements.txt)

**Comment by do3cc** [comment]
I know that feeling, but we should do it right, else everything becomes confusing

**Comment by do3cc** [comment]
Just to make it crystal clear: Nobody is against changing the best practices. regarding bootstrap.py.
But first, it must be changed in zc.buildout.
Then in the docs, and then here.
We are the end of the chain, not the beginning.
If we start doing it here, we make things worse for outsiders, because the documentation for how to "bootstrap" is inconsistent.
And some people start yelling at us on community.plone.org that we are unworthy, bad developers.
