### ISSUE TITLE
Support Barceloneta as base theme

### ISSUE THREAD

**Issue by davilima6** [plone/bobtemplates.plone#154]
With a ZopeSkel theme skeleton in Plone 4, we get Sunburst as base theme after installing the package. That should be the default behavior for mr.bob generated theme packages too. [[See reference.]](https://community.plone.org/t/adding-theme-base-options/2315)

It's also the recommended method for theming in https://training.plone.org/5/theming/theme-package.html#css-and-js-resources

We could add this as a question when generating the package. If the answer is positive, mr.bob would add bits to metadata.xml, registry.xml and LESS/JS placeholders (including requirejs wrappers/boilerplate) in [`theme/static`](https://github.com/plone/bobtemplates.plone/tree/master/bobtemplates/plone_addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/theme).

**Comment by agitator** [comment]
probably related to https://github.com/plone/bobtemplates.plone/issues/131

**Comment by tisto** [comment]
@davilima6 that would be quite useful indeed. The only thing I'm concerned about is that theming in Plone 4 and 5 is quite different and it might be hard to maintain two versions in the same template. It might be useful to create a separate product. 

@sneridagh @bloodbare what's your opinion on that?

**Comment by davilima6** [comment]
This branch contains WIP that addresses this issue: https://github.com/plone/bobtemplates.plone/tree/support_for_theming_variations

@iham, what would be the status there? Anything missing before we can have a PR?

**Comment by MrTango** [comment]
I close this, because we are having Barceloneta included as the default theme already.
For Plone 4 the ussage of ZopeSkel should be enough.
It doesn't make sense to suport this in the same package here, because it's quite different.
But basically with some changes to the rules, it should even work for Plone 4 with Barceloneta.
Because we include all Barceloneta resources and the template.
But i would recommend to go with ZopeSkel for Plone 4.
