### ISSUE TITLE
Follow indentation best practices for non-python files (2 blanks instead of 4).

### ISSUE THREAD

**Issue by tisto** [plone/bobtemplates.plone#24]

**Comment by iham** [comment]
+1

**Comment by pbauer** [comment]
The best practice for zcml and xml is not 2 blanks but: "Indentation of 2 characters to show nesting, 4 characters to list attributes on separate lines."
See http://docs.plone.org/develop/styleguide/python.html#indentation

**Comment by tisto** [comment]
@gforcada I strongly disagree. Mixing styles sucks, no matter if we have an automated check or not. This is especially true for a package that is a starting point for new developers. I open that ticket because people started to merge pull request that used a different type of indentation than the rest of the files had.

**Comment by gforcada** [comment]
@tisto having an issue opened asking for World Peace will not bring such, just state that. That's my point, as long as you don't point to all and every single contributor to this issue on each pull request you will get mixed spaces, tabs and whatnot.

We can clean it afterwards and double/triple check it everytime (I usually do that, I developed a sixth sense on that) but I prefer to rely on tools to do that for me so I can relax and focus on the pull request rather on the spaces.

A point release with a full pass on all the files is doable, but not for each release/pull request, that's adding too much burden to the reviewers/dealing everything because of that.

But I will leave it open if you feel better this way :-)

**Comment by loechel** [comment]
One element for that is an .editorconf file that sets the corresponding settings in editors. #206 and #216 does set this.
A second thing should be a linter that check those files. And help to enforce that.

**Comment by MrTango** [comment]
@tisto do you still see a reason to leave this open?
We have quite a view checks in codeanalysis and i'm with @gforcada that the best way to make sure every body sticks to the rules is enforcing them this way. If anything is mission, we should state it and try to add it to our codeanalysis checks.
