### ISSUE TITLE
Full-featured theme subtemplate

### ISSUE THREAD

**Issue by erral** [plone/bobtemplates.plone#240]
We have been discussing about the `theme_package` and the `theme` subtemplate at work, and think that could be nice to have a subtemplate that adds a theme but not an empty one but a similar one to the one created by the `theme_package` template.

This way you can add a complete theme into an addon.

This has come in a conversation that we had where we try to create just one package for our client websites, because almost always the content types created for a customer are tightly coupled to the theme and viceversa.

If this is interesting we can work on this

@nruiz @libargutxi

**Comment by MrTango** [comment]
The theme subtemplate does not provide barceloneta, because usually if one creates a Plone theme from a mockup, she does not need all the barceloneta stuff, but copies the static files into the theme and creates the rules to fit the structure in the static files.

We can create a second theme sub templates called theme_barceloneta.
Or another way to solve your needs might be to extend the theme_package a bit, so you could use this as a base for other subtemplates. I'll probably chnage the structure of the addon template a bit, so that we will have a ``.bobtemplate.cfg`` in the package root which contains the infos which are currently in the setup.cfg. The reason for this is, that we also have templates like the buildout template which are not packages and therefor does not have a setup.cfg. But we need some metadata. So a more generic way of storing theme might be better.

**Comment by MrTango** [comment]
@erral would you want to work on this topic and add it in a PR?
