### ISSUE TITLE
backend.xml pulls the all scripts again, causing non deterministic JS errors

### ISSUE THREAD

**Issue by sneridagh** [plone/bobtemplates.plone#320]
This rule:
`    <after css:theme-children="head" css:content="head script" />`
is present in both rules.xml and in backend.xml, so that causes to be added twice:

<img width="812" alt="screenshot 2018-09-28 at 10 28 52" src="https://user-images.githubusercontent.com/486927/46197216-6fa4e680-c309-11e8-8872-b426f8c7e3b3.png">

In case that you are including backend.xml in your rule set.

This should be changed in barceloneta (https://github.com/plone/plonetheme.barceloneta/issues/158) and in the templates as well.

**Comment by MrTango** [comment]
What about having the same note also inside the main rules.xml?
So that one see's it on both sides. In fact, we could even remove it from the backend.xml and just document that, one has to include this in the main rules.xml, either inside the backend block or if needed for the frontend too, outside of it. 

We also have the case that, one just includes the backend.xml directly from barceloneta, like we do with the newer "theme"-subtemplate in bobtemplates.plone. This is meant to be a better start for integrating existing themes, which are not just customizing barceloneta. We still use the backend as it is, but can't customize the backend.xml. So your change in plonetheme.barceloneta is not just cosmetic ;)
