### ISSUE TITLE
bobtemplate.plone breaks search for special characters in Plone

### ISSUE THREAD

**Issue by pbauer** [plone/bobtemplates.plone#335]
See https://github.com/plone/Products.CMFPlone/issues/2599

**Comment by MrTango** [comment]
I had to revert my fix, it's used by the portlet template. In my opinien this has to be fixed in Plone, so that Unidecode>=0.04.16 is no longer a problem, as this is an already many years old version, so it's time to move on. Even the odest version of slugify requires a newer version.

I'm open to any replacement for the library.

**Comment by pbauer** [comment]
Fixed with plone/bobtemplates.plone@1a76769 in `bobtemplates.plone = 3.5.2`
