### ISSUE TITLE
Create bobtemplate for Dexterity.

### ISSUE THREAD

**Issue by tisto** [plone/bobtemplates.plone#35]
So we can replace zopeskel here:

https://github.com/plone/documentation/blob/master/develop/addons/dexterity.rst

Related documentation issue: https://github.com/plone/documentation/issues/193#issuecomment-74475961

Question is: do we want to have dexterity/theme/etc as a separate bobtemplate or do we want to integrate it into the existing plone_addon template.

cc @svx

**Comment by djowett** [comment]
Hi, my thoughts are
  mr.bob templates can overwrite each other's output (in a good way) pretty easily - the only reason they need to know about each other is to not clobber each other's output. (I believe paster/zopeskel localcommands were much more entangled in their "parents").

My suggestions:
- Since you may want to add dexterity behaviors / content types multiple times - then you are more or less *forced* to have a different bobtemplate
- In order to minimize clobbering worries - try to keep each new template working in different subfolders - e.g. this dexterity one in "content"

**Comment by tisto** [comment]
@djowett Do you have an example of how to override the template output?

I was thinking about using different folders as well. Though, there will always be the need to register even a folder in configure.zcml and/or a gs setup step.

Things would be a lot easier if mr.bob would support depending on existing templates:

https://github.com/iElectric/mr.bob/issues/31

**Comment by djowett** [comment]
It's very easy (unless I misunderstood):

    $ ../bin/mrbob -O collective.myaddon2 bobtemplates:plone_addon
    # I would recommend a git init ; git add . ; git commit here in real situations
    $ ../bin/mrbob -O collective.myaddon2 mrbob:template_sample/
    Welcome to mr.bob interactive mode. Before we generate directory structure, some questions need to be answered.

    Answer with a question mark to display help.
     Values in square brackets at the end of the questions show the default value if there is no answer.

     --> What is your name?: Daniel

     --> How old are you? [24]: 135

     --> Enter password: 

    Generated file structure at /home/daniel/dev/Plone/Development/highfields_ph2.1/src/collective.myaddon2
    $ ls -ltr collective.myaddon2 
     ....
     -rw-rw-r-- 1 daniel daniel   89 Feb 12 11:47 CHANGES.rst
     -rw-rw-r-- 1 daniel daniel   83 Feb 16 11:32 sample.txt

     $ more collective.myaddon2/sample.txt 
     My name is Daniel. I am 135 years old.
 
     This is my password to everything:  doodah

**Comment by djowett** [comment]
Yep, I think different folders is a good convention.  More specifically: 1 folder <=> 1 bobtemplate
That would mean that dexterity behaviours & content types are generated from the same bobtemplate, but since they need to avoid clobbering each other that's no bad thing IMO.

I saw https://github.com/iElectric/mr.bob/issues/31, and it scares me to be honest.  I think that it would make things easier to develop now & then horrible to maintain. You would have problems like the main template not be able to change because other templates depended on it's variables, then if you did change variables, you would need version pins between templates. 

I might not be thinking that through thoroughly, but `mrbob` is nice principally because it's simple - this goes the way of `paster` making it too complex to maintain beyond a few experts, for not much benefit.  Am I wrong?

I think an option in a mrbob template to limit the files that it wants to clobber would be much more useful.

Thoughts?

**Comment by tisto** [comment]
I agree. Simplicity is the most important asset of mr.bob. I'd rather live with limited functionality to keep things simple.

**Comment by gforcada** [comment]
So let's go forward with different templates, i.e. bobtemplates.dexterity and so on until mr.bob has a story here...
