### ISSUE TITLE
Can we rationalize the plone.version question?

### ISSUE THREAD

**Issue by djowett** [plone/bobtemplates.plone#36]
Currently it is:

```
plone.version.question = Plone version
plone.version.help = Which Plone version would you like to use?
plone.version.default = 4.3.4
plone.version.post_ask_question = bobtemplates.hooks:post_plone_version
```

This is fed into:
i) Pypi Trove classifers (even though 4.3.4 is invalid)
ii) `plone.is_plone5` variable

What niggles me is that the implication that an addon **IS** plone 5 is incorrect, we should say **supports** plone 5 - and perhaps more importantly we should work the same out for plone 4.

I'd like to see the above question (& help) changed to something like "_Target_ Plone version" & then follow up with:

```
 plone.support_version4.question = Support Plone 4?
 plone.support_version4.default = True
 plone.support_version4.pre_ask_question = bobtemplates.hooks:skip_support_qu_if_we_know

 plone.support_version5.question = Support Plone 5?
 plone.support_version5.default = True
 plone.support_version5.pre_ask_question = bobtemplates.hooks:skip_support_qu_if_we_know
```

(With a slightly shorter hook function name ;-) )

This would help make code tidier for Plone 5 if we knew the product wasn't planning to support Plone4

Any objections/thoughts?

**Comment by tisto** [comment]
The plone version / plone 5 question are strange indeed. Though, we have to allow people to choose which buildout plone version they want to use (this is what the version question really is about). This is also important for the test matrix.

The current plone_5 question is only used for the testing layer, so the question is really "do you want to use ATContentTypes or plone.app.contenttypes for your test layer".

We should definitely give this some thought and come up with a better solution and/or naming.

**Comment by pbauer** [comment]
I just realised that I forgot to commit a local change that used that question to extend from https://raw.github.com/collective/buildout.plonetest/master/plone-5.x.cfg instead of https://raw.github.com/collective/buildout.plonetest/master/plone-4.3.x.cfg. We should add this and change the biuldout.cfg snd travis.cfg accordingly.

**Comment by tisto** [comment]
To be honest I'm not sure if depending on buildout.plonetest is a good idea at all. I did something similar with buildout.jenkins and I came to the conclusion that it is fundamentally wrong to put an unversioned buildout configuration to some repo that other can extend. 

It is impossible to change things there (because it will break every buildout that depends on this) and it will always be a blackbox for users. The buildout configurations in buildout.plonetests are scattered across different files and (at least for me) it is impossible to figure out what goes on where (this even became clearer when I gave a buildout training last month). 

It is far easier to just extend dist.plone.org. Only a few lines of additional code is necessary and people at least have a chance to understand what they are doing. I'm not 100% of this yet, but I'm pretty sure that what we are doing in buildout.plonetest right now is wrong (we would need at least to version things and run regular tests on the buildouts).

On the matter of the additional question, I think we should try hard to reduce the overall number of questions. We should just ask about the exact Plone version number (e.g. 4.3.4, 5.0a1) that should be used for the buildout configuration. If people want tests (not sure if this should be a question at all) we also need to ask about p.a.contenttypes or ATContentTypes. Then we can remove to question about Plone5, right?

**Comment by iham** [comment]
as plone 5 is the current standard:
can we upgrade to that version as the default?

and in general:
shall we search a way to get a list of supported versions?
or would it be better to split the versions? 4.x, 5.x, 6.x, ...

when we maintain lots of versions (with more or less big differences) we end up having lots of files, which must be cleaned afterwards and even more if/else hacks into the *.bob files (like buildout.cfg, setup.py, etc)

**Comment by gforcada** [comment]
This is largely covered already, feel free to reopen if needed.

**Comment by djowett** [comment]
Yep, that's fine - the Trove classifier is correct now it seems.
For the other points, I'll just accept we are all grown up Plone Devs :)
