### ISSUE TITLE
content_type subtemplate does not ask for class

### ISSUE THREAD

**Issue by erral** [plone/bobtemplates.plone#365]
Since bobtemplates.plone 4.0 when using the content_type subtemplate to add a content_type to an addon does not ask for "Create a content type class?"

**Comment by erral** [comment]
This is a bit strange because the question is indeed in the .mrbob.ini file:

https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone/content_type/.mrbob.ini#L51

**Comment by erral** [comment]
I see that there is an additional check now:

https://github.com/plone/bobtemplates.plone/commit/235ac45615236304ed08c75cd537df09ad8329b9

**Comment by erral** [comment]
@MrTango why is this change needed? https://github.com/plone/bobtemplates.plone/commit/235ac45615236304ed08c75cd537df09ad8329b9

**Comment by MrTango** [comment]
We where using a fake behavior (Interface) before that to have a marker which identifies the CT, but this is not a good solution and will give warning in the future, since it was not a real behavior. To have a way of identifying a TTW based CT, we need the base class with the implemented marker interface. If you choose Python schema instead of supermodel (XML) you still have this question.
