### ISSUE TITLE
isort configuration in conflict with Plone's styleguide?

### ISSUE THREAD

**Issue by wesleybl** [plone/bobtemplates.plone#449]
The configuration of the `isort` forces the grouping of imports. For example in [testing.py](https://github.com/plone/bobtemplates.plone/blob/553c5859973c3dbd4bbe7575ca1d8150ad2608d7/bobtemplates/plone/addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/testing.py.bob#L6-L14). Doesn't that conflict with [Plone's styleguide](https://docs.plone.org/develop/styleguide/python.html#grouping-and-sorting)?

**Comment by MrTango** [comment]
Right now it ios compatible with black, because we are using black to autoformat Python.
Tha is indeed not in line with the styleguide. But the solution would be to update the styleguide, rather than not using black.
My feeling is, that most people are using black nowerdays in Python land and many Plone people do too. 
There is actually an accepted PLIP using black in Plone.
https://github.com/plone/Products.CMFPlone/issues/2754
We will add more checks based on black in bobtemplates.plone in time and moving forward into this direction.

**Comment by wesleybl** [comment]
@MrTango in fact, who does this is the isort and not black. It is possible to use black and configure isort so as not to group imports. Should we do this?

**Comment by yurj** [comment]
https://github.com/plone/Products.CMFPlone/issues/3497
