### ISSUE TITLE
update theme_barceloneta to 2.1.10

### ISSUE THREAD

**Issue by yurj** [plone/bobtemplates.plone#460]
Hi!
 bobtemplates create theme barceloneta with version 2.1.2
 barceloneta/BARCELONETA-VERSION.rst
2.1.2

Will the template be updated with other versions (latest is 2.1.10)?

**Comment by MrTango** [comment]
right now this is a manual tasks, we are wokring on the Plone 6 version and will probably not spent much time on the older version to update barceloneta resources there. feel free to do it yourself and do a PR.
I'll leave this open here, in case someone wants to jump in.
In the future the plan is to have the resources released on npm, so that updates are easier.

**Comment by MrTango** [comment]
this is now handled by the package.json and can be updated there
