### ISSUE TITLE
Robot tests for generated addon aren't included in testsuite

### ISSUE THREAD

**Issue by djowett** [plone/bobtemplates.plone#69]
cd src
    ../bin/mrbob -O my.addon bobtemplates:plone_addon
    [answer questions]
    cd ..
    update buildout.cfg 
    bin/buildout
    $ bin/test -s my.addon --list-tests
    Listing my.addon.testing.MyAddonLayer:IntegrationTesting tests:
    test_browserlayer (my.addon.tests.test_setup.TestSetup)
    test_product_installed (my.addon.tests.test_setup.TestSetup)
    test_uninstall (my.addon.tests.test_setup.TestSetup)

As you can see the robot test in `test_example.robot` is missing, but I can't see why?

updates to buildout.cfg were the obvious 3 lines....

[sources]
+my.addon = fs my.addon
 collective.behavior.banner = git https://github.com/collective/collective.behavior.banner.git
 
 [buildout]
test-packages =
+    my.addon[test]
 
 
eggs =
     collective.behavior.banner
+    my.addon

**Comment by gforcada** [comment]
The reason is this line: https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/tests/test_robot.py.bob#L3

robot tests are only run at that level which is above 1, the default for zope.testrunner, thus the test is not executed.

If you try with ``./bin/test --at-level 5`` (https://github.com/plone/plone.app.testing/blob/master/plone/app/testing/interfaces.py#L16) then the robot test will run.

**Comment by djowett** [comment]
Oh, thanks Gil.... sorry for the noise!

**Comment by tisto** [comment]
The recommended way would be "bin/test --all" to run all tests (including robot).

**Comment by tisto** [comment]
Maybe we should make sure that this is covered by the documentation. I guess @djowett will not be the only person who will run into this...
