### ISSUE TITLE
Coverage/Coveralls does not grip.

### ISSUE THREAD

**Issue by jensens** [plone/bobtemplates.plone#93]
For some reason it does not show coverage results at  https://coveralls.io/github/plone/bobtemplates.plone

**Comment by mauritsvanrees** [comment]
Looks like coveralls has never run for us.

In our `.travis.yml` we are not creating a coverage report. So we should call `bin/createcoverage`. But it we add this part, like we do for the addons we create, and we call it, it quits immediately because it expects there to be a `bin/test` that is a python script, and for us it is a shell script.

I briefly tried the next python code for bin/test, but then coverage tells us that we have 100% test coverage within the three lines of the`bin/test` script itself, which is not quite what we are after...:

```
import subprocess
import sys
sys.exit(subprocess.call('./bin/nosetests'))
```

If I hack the createcoverage script to run `bin/nosetests`, it goes better. It even says 100% coverage, but, well, we are only testing our one line `__init__.py`....:

![schermafbeelding 2015-09-16 om 20 04 56](https://cloud.githubusercontent.com/assets/210587/9913716/794c488c-5cae-11e5-84fb-33551872338d.png)

Our `hooks.py` file is not tested at all like this, because it is not called.  The original `bin/test` script does call it, but in this setup we would only call `bin/nosetests`.

Anyway, if we want coverage reports, the first step would be:
add an option to the createcoverage recipe so we can tell it to run bin/nosetests instead of bin/test.

Or does anyone know an alternative to createcoverage that we can use?

**Comment by mauritsvanrees** [comment]
Fixed.
